import Layout from '@/components/ui/Layout'
import './_styles/reset.css'
import './_styles/root.css'
import './_styles/styles.css'
import './_styles/icons.css'

export const metadata = {
    title: { template: ' David le Codeur | %s', default: 'David le Codeur' },
    description: 'Generated by create next app',
    creator: 'David Blard',
    siteName: 'David le codeur',
    category: 'web development',
}

export default function RootLayout(props) {
    return <Layout>{props.children}</Layout>
}
