import './_styles/reset.css'
import './_styles/root.css'
import './_styles/styles.css'
import client from '@/tina/__generated__/client'

export const metadata = {
    title: { template: ' David le Codeur | %s', default: 'David le Codeur' },
    description: 'Generated by create next app',
    creator: 'David Blard',
    // absolute: 'ggg',
}

export default function RootLayout(props) {
    return <>{props.children}</>
}
